define(function(require, exports, module) {
var __disableStrictMode__ = "use strict";

/*
 * Copyright (C) 2005 - 2020 TIBCO Software Inc. All rights reserved. Confidentiality & Proprietary.
 * Licensed pursuant to commercial TIBCO End User License Agreement.
 */
module.exports = {
  CONSTANT_GROUP: 'CONSTANT_GROUP',
  DATA_SOURCE: 'DATA_SOURCE',
  DATA_SOURCE_GROUP: 'DATA_SOURCE_GROUP',
  TABLE: 'TABLE',
  DERIVED_TABLE: 'DERIVED_TABLE',
  TABLE_GROUP: 'TABLE_GROUP',
  FIELD: 'FIELD',
  FIELD_REFERENCE: 'FIELD_REFERENCE',
  CALC_FIELD: 'CALC_FIELD',
  FILTER_EXPRESSION: 'FILTER_EXPRESSION',
  COMPLEX_FILTER: 'COMPLEX_FILTER',
  TABLE_REFERENCE: 'TABLE_REFERENCE',
  JOIN_TREE: 'JOIN_TREE',
  JOIN_ALIAS: 'JOIN_ALIAS',
  JOIN: 'JOIN',
  COMPLEX_JOIN: 'COMPLEX_JOIN',
  JOIN_EXPRESSION: 'JOIN_EXPRESSION',
  CONSTANT_JOIN_EXPRESSION: 'CONSTANT_JOIN_EXPRESSION',
  DATA_ISLAND: 'DATA_ISLAND',
  PRESENTATION_SET: 'PRESENTATION_SET',
  PRESENTATION_FIELD: 'PRESENTATION_FIELD'
};

});